POST http://localhost:30000/api/clothing/add
Content-Type: multipart/form-data; boundary=WebTestBoundary

--WebTestBoundary
Content-Disposition: form-data; name="category"
Content-Type: text/plain

top

--WebTestBoundary
Content-Disposition: form-data; name="subcategory"
Content-Type: text/plain

shirt

--WebTestBoundary
Content-Disposition: form-data; name="colors"
Content-Type: text/plain

Black, White

--WebTestBoundary
Content-Disposition: form-data; name="tags"
Content-Type: text/plain

winter

--WebTestBoundary
Content-Disposition: form-data; name="styles"
Content-Type: text/plain

댄디, 포멀

--WebTestBoundary
Content-Disposition: form-data; name="image"; filename="test2.jpg"
Content-Type: image/jpeg

< ./test2.jpg

--WebTestBoundary--
