### Add a new outfit
POST http://localhost:30000/api/outfit/add
Content-Type: application/json

{
  "date": "2022-12-01",
  "schedule": "발표",
  "clothingIds": [
    1
  ],
  "addressName": "서울특별시 강남구 역삼동",
  "maxTemperature": 10,
  "minTemperature": 5,
  "precipitationType": "비",
  "sky": "맑음"
}

### Get all outfits
GET http://localhost:30000/api/outfit/all
Accept: application/json

### Get a single outfit by ID
GET http://localhost:30000/api/outfit/1
Accept: application/json

### Get outfits by date
GET http://localhost:30000/api/outfit/date
Content-Type: application/json

{
  "date": "2022-12-01"
}

### Update an outfit
PUT http://localhost:30000/api/outfit/update
Content-Type: application/json

{
  "id": 1,
  "date": "2022-12-02",
  "schedule": "work",
  "clothingIds": [1]
}

### Delete an outfit
DELETE http://localhost:30000/api/outfit/1